# Change these first

owner: chashguru # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
- name: Facebook App
  url: https://dash11.comm100.io/api/facebookapp/health
- name: WhatsApp Cloud
  url: https://dash11.comm100.io/api/whatsappcloud/health
- name: Ticketing
  url: https://dash11.comm100.io/api/ticketing/health
- name: Telnyx 
  url: https://dash11.comm100.io/api/telnyxsmsadapter/health
- name: Contact SSO  
  url: https://dash11.comm100.io/api/contactsso/health
- name: Deltapath  
  url: https://dash11.comm100.io/api/deltapath/health
- name: Messenger
  url: https://dash11.comm100.io/api/messenger/health
- name: ACPNS
  url: https://dash11.comm100.io/api/acpns/health
- name: Email App
  url: https://dash11.comm100.io/api/emailapp/health

status-website:
  baseUrl: /monitoring # where "repo" is your repository name
  name: Production Monitoring
  logoUrl: https://www.comm100.com/wp-content/uploads/images/logo-comm100-2022.svg
  faviconSvg: https://www.comm100.com/wp-content/uploads/2023/01/image/png/Outreach-icon-update.png

- name: Axios Action
  uses: actionsflow/axios@v1
