# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
- name: Facebook App
  url: https://dash11.comm100.io/api/facebookapp/health
- name: WhatsApp Cloud
  url: https://dash11.comm100.io/api/whatsappcloud/health
- name: Ticketing
  url: https://dash11.comm100.io/api/ticketing/health
- name: Telnyx 
  url: https://dash11.comm100.io/api/telnyxsmsadapter/health
- name: Contact SSO  
  url: https://dash11.comm100.io/api/contactsso/health
- name: Deltapath  
  url: https://dash11.comm100.io/api/deltapath/health
- name: Messenger
  url: https://dash11.comm100.io/api/messenger/health
